title: Swetha Ganapathi Raman
theme: jekyll-theme-minimal
description: > 
  Work Experience:
  - Data Scientist at Instacart, Toronto
  - Data Scientist at Tesla, Palo Alto
  - Data Analyst at VMWare, Palo Alto
  <br><br>
  <a href="https://www.linkedin.com/in/swetharaman</a> 
