title: <p align="center"> Swetha Ganapathi Raman </p>
theme: jekyll-theme-minimal
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/swetharaman/">LinkedIn</a> |
  <a href="https://github.com/swethag04">GitHub</a>
  </p>

  <p align="justify">
  I am an experienced Data Scientist with 4+ years of experience working in Instacart, Tesla and VMWare.
  <br><br>
  I am currently looking for an opportunity in AI/ML space with a focus on Gen AI and NLP.
  <br><br>
  </p>
  
